ALTER TABLE posts ALTER COLUMN PostEditContent DROP NOT NULL;
ALTER TABLE posts ALTER COLUMN PostDeleted SET DEFAULT false;
ALTER TABLE posts ALTER COLUMN PostDeletedBy DROP NOT NULL;
ALTER TABLE posts ALTER COLUMN PostDeleteTime DROP NOT NULL;
